In [87]:
import re
import pandas as pd
from openpyxl import load_workbook
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

#Gathering Data Mentorship

###Data Mentorship GKS U

In [88]:
dataset_gksu = ('/content/drive/MyDrive/Data Analyst HelloCation/Weekly 1 (Dataset MENTORSHIP)/mentorship-gksu.csv')

gks_u= pd.read_csv(dataset_gksu)
gks_u.head(5)

,Timestamp,Nama Lengkap,Asal Instansi,Jurusan,Domisili,Umur,No. HP aktif,Nama Acc Instagram,Alasan mengikuti mentorship di Hellocation?,Dari mana anda mengetahui informasi mentorship ini?,Pilih kelas Mentorship yang Anda inginkan,Beasiswa apa yang ingin diikuti?,Jenjang studi yang ingin di apply?,Rencana Univ yang dituju dan jurusan,Tanggal transfer
0,7/13/2023 21:11:01,rima,sma thursina iibs,ips,bekasi,19,82397070770,-,mau persiapan ikut gks,lewat di timeline ig,Kelas Private,GKS (Korea Selatan),S1,NaN,7/13/2023
1,7/15/2023 17:37:03,Adriana Salsabila Irawan,SMAN 4 SUBANG,IPS,Buana Subang Kencana blok F64 RT.48 RW.16 Sokl...,18,87822380897,@adrianaaiss,butuh bimbingan beasiswa gks,dari tiktok hellocation,Kelas Private,GKS (Korea Selatan),S1,NaN,7/15/2023
2,7/20/2023 22:27:03,Hernio Bayuaji Hutomo,Universitas Airlangga,-,Palu,27,85713468183,Herniohoetomo,Ingin lebih tau tentang beasiswa GKS,Iklan di IG,Kelas Reguler,GKS,S2,Yonsei - Global MBA,7/20/2023
3,7/21/2023 7:57:10,Willy Yudistira,SMAN 1 Maos,IPA,"Cilacap, Jawa Tengah",18,81235324019,@willyudistira,Belajar,Postingan hellocation,Kelas Reguler,GKS,S1,-,7/21/2023
4,7/21/2023 18:38:45,YAYANG DIAZ ASTI PUTRI,SMKN 4 Malang,Rekayasa Perangkat Lunak,Malang,18 tahun,8563269623,@yayanggdiaz,Karena ingin mendaftar beasiswa GKS (Global Ko...,Dari postingan instagram @hellocation,Kelas Reguler,Beasiswa GKS (Korea Selatan),S1,Korea University - Industrial Management Engin...,7/21/2023

### Data Mentorship GKS G

In [89]:
dataset_gksg = ('/content/drive/MyDrive/Data Analyst HelloCation/Weekly 1 (Dataset MENTORSHIP)/mentorship-gksg.csv')

gks_g= pd.read_csv(dataset_gksg)
gks_g.head(5)

,Timestamp,Nama Lengkap,Asal Instansi,Jurusan,Domisili,Umur,No. HP aktif,Nama akun instagram,Alasan ingin mengikuti mentorship,Pilih kelas Mentorship yang Anda inginkan
0,12/12/2022 21:25:50,Nurhalija,STIEM Palopo,Akuntansi,Palopo,27,82264812346,nurhalija95,Ingin dibimbing dalam mempersiapkan diri utk m...,NaN
1,04/01/2023 20:17:26,Mauliandini Nur Noviasri,Universitas Brawijaya,Perencanaan Wilayah dan Kota,Jakarta,36,81908200974,mauliandininoviasri,Rencana melanjutkan pendidikan S2 melalui beas...,Kelas Reguler
2,04/01/2023 21:01:02,Nabila Putri Candisa,Universitas Prasetiya Mulya,Marketing,Tangerang,28,85720368532,ncandisa,Ingin mendaftar GKS-G dan butuh mentorship ser...,Kelas Private
3,05/01/2023 14:02:34,Luchia Pri Utama,Universitas Bakrie,Hubungan Internasional,Jakarta,26,87766383553,luchiaerina,Persiapan untuk daftar GKS 2023,Kelas Reguler
4,08/01/2023 22:46:41,Elisabet Suryani Wianto,Universitas Trisakti,Akuntansi,Semarang,25,83838959450,elisabetsw_,Tahun ini baru pertama kali mau coba daftar GK...,Kelas Private

###Data Mentorship GKS Sheet 3

In [90]:
dataset_gks_sheet = ('/content/drive/MyDrive/Data Analyst HelloCation/Weekly 1 (Dataset MENTORSHIP)/mentorship-sheet3.csv')

gks_sheet= pd.read_csv(dataset_gks_sheet)
gks_sheet.head(5)

,Timestamp,Nama Lengkap,Asal Instansi,Jurusan,Domisili,Umur,No. HP aktif,Nama akun instagram,Alasan ingin mengikuti mentorship,Pilihan Kelas,Apakah kamu bersedia melakukan pembayaran sebesar Rp200.000 untuk kelas Reguler?,Apakah kamu bersedia menghadiri Onboarding yang akan dilaksanakan pada tanggal 6 Agustus 2022?,Apakah kamu bersedia mengikuti mentorship pada tanggal yang sudah ditentukan?,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,29/07/2022 12:19:37,Alexandra,SMK Analis Kimia Bogor,Graduated (Analis Kimia),Bogor,19,81514090657,alexa.drrr,Alasan saya mengikuti program mentorship adala...,Reguler,Ya,Ya,Ya,NaN,NaN,NaN
1,29/07/2022 19:19:32,Nia Veronica Agustin,Universitas Riau,Pendidikan Bahasa dan Sastra Indonesia,Pekanbaru kota,24,85271453121,niaveronicaagustin,Saya akan mendaftar beasiswa GKS tahun 2023.,Reguler,Ya,Ya,Ya,NaN,NaN,NaN
2,30/07/2022 20:28:50,Fira Amalianda,President University,Management,"Kab.kuantan singingi, Riau",19,82170427303,Firamalianda,Alasan aku mengikuti program ini karena aku in...,Reguler,Ya,Ya,Ya,NaN,NaN,NaN
3,31/07/2022 12:51:54,Sajida Mustifa Radhianajla,SMAN 3 TANGERANG SELATAN,IPA,TANGERANG selatan,18,85846985708,s.mustifaa_,"Dengan mendapatkam mentorships, aku bisa menin...",Premium,Ya,Ya,Ya,NaN,NaN,NaN
4,31/07/2022 22:19:55,Stephanie Candy Sabella,SMA Pahoa,IPS,Tangerang,18,81212850979,stephanie.cs,Sejak kecil saya selalu bermimpi agar bisa kul...,Premium,Ya,Ya,Ya,NaN,NaN,NaN

#Assesing Data Mentorship

###Tampilkan data mentorship-gksu

In [91]:
gks_u.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Timestamp                                            30 non-null     object
 1   Nama Lengkap                                         30 non-null     object
 2   Asal Instansi                                        30 non-null     object
 3   Jurusan                                              30 non-null     object
 4   Domisili                                             30 non-null     object
 5   Umur                                                 30 non-null     object
 6   No. HP aktif                                         30 non-null     object
 7   Nama Acc Instagram                                   30 non-null     object
 8   Alasan mengikuti mentorship di Hellocation?          30 non-null     object
 9   Dari mana anda mengetahui informasi mentorship ini?  30 non-null     object
 10  Pilih kelas Mentorship yang Anda inginkan            30 non-null     object
 11  Beasiswa apa yang ingin diikuti?                     30 non-null     object
 12  Jenjang studi yang ingin di apply?                   30 non-null     object
 13  Rencana Univ yang dituju dan jurusan                 28 non-null     object
 14  Tanggal transfer                                     30 non-null     object
dtypes: object(15)
memory usage: 3.6+ KB

In [92]:
gks_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 10 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Timestamp                                  38 non-null     object
 1   Nama Lengkap                               38 non-null     object
 2   Asal Instansi                              38 non-null     object
 3   Jurusan                                    38 non-null     object
 4   Domisili                                   38 non-null     object
 5   Umur                                       38 non-null     object
 6   No. HP aktif                               38 non-null     object
 7   Nama akun instagram                        38 non-null     object
 8   Alasan ingin mengikuti mentorship          38 non-null     object
 9   Pilih kelas Mentorship yang Anda inginkan  37 non-null     object
dtypes: object(10)
memory usage: 3.2+ KB

In [93]:
gks_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 16 columns):
 #   Column                                                                                          Non-Null Count  Dtype
---  ------                                                                                          --------------  -----
 0   Timestamp                                                                                       42 non-null     object
 1   Nama Lengkap                                                                                    42 non-null     object
 2   Asal Instansi                                                                                   42 non-null     object
 3   Jurusan                                                                                         42 non-null     object
 4   Domisili                                                                                        42 non-null     object
 5   Umur                                                                                            42 non-null     object
 6   No. HP aktif                                                                                    42 non-null     object
 7   Nama akun instagram                                                                             42 non-null     object
 8   Alasan ingin mengikuti mentorship                                                               42 non-null     object
 9   Pilihan Kelas                                                                                   32 non-null     object
 10  Apakah kamu bersedia melakukan pembayaran sebesar Rp200.000 untuk kelas Reguler?                42 non-null     object
 11  Apakah kamu bersedia menghadiri Onboarding yang akan dilaksanakan pada tanggal 6 Agustus 2022?  42 non-null     object
 12  Apakah kamu bersedia mengikuti mentorship pada tanggal yang sudah ditentukan?                   42 non-null     object
 13  Unnamed: 13                                                                                     0 non-null      float64
 14  Unnamed: 14                                                                                     0 non-null      float64
 15  Unnamed: 15                                                                                     3 non-null      object
dtypes: float64(2), object(14)
memory usage: 5.4+ KB

###Cek missing value dan Hapus

In [94]:
gks_u.isna().sum()

Timestamp                                              0
Nama Lengkap                                           0
Asal Instansi                                          0
Jurusan                                                0
Domisili                                               0
Umur                                                   0
No. HP aktif                                           0
Nama Acc Instagram                                     0
Alasan mengikuti mentorship di Hellocation?            0
Dari mana anda mengetahui informasi mentorship ini?    0
Pilih kelas Mentorship yang Anda inginkan              0
Beasiswa apa yang ingin diikuti?                       0
Jenjang studi yang ingin di apply?                     0
Rencana Univ yang dituju dan jurusan                   2
Tanggal transfer                                       0
dtype: int64

In [95]:
gks_g.isna().sum()

Timestamp                                    1
Nama Lengkap                                 1
Asal Instansi                                1
Jurusan                                      1
Domisili                                     1
Umur                                         1
No. HP aktif                                 1
Nama akun instagram                          1
Alasan ingin mengikuti mentorship            1
Pilih kelas Mentorship yang Anda inginkan    2
dtype: int64

In [96]:
gks_sheet.isna().sum()

Timestamp                                                                                          0
Nama Lengkap                                                                                       0
Asal Instansi                                                                                      0
Jurusan                                                                                            0
Domisili                                                                                           0
Umur                                                                                               0
No. HP aktif                                                                                       0
Nama akun instagram                                                                                0
Alasan ingin mengikuti mentorship                                                                  0
Pilihan Kelas                                                                                     10
Apakah kamu bersedia melakukan pembayaran sebesar Rp200.000 untuk kelas Reguler?                   0
Apakah kamu bersedia menghadiri Onboarding yang akan dilaksanakan pada tanggal 6 Agustus 2022?     0
Apakah kamu bersedia mengikuti mentorship pada tanggal yang sudah ditentukan?                      0
Unnamed: 13                                                                                       42
Unnamed: 14                                                                                       42
Unnamed: 15                                                                                       39
dtype: int64

In [99]:
#hapus missing value
gks_u.dropna()

,Timestamp,Nama Lengkap,Asal Instansi,Jurusan,Domisili,Umur,No. HP aktif,Nama Acc Instagram,Alasan mengikuti mentorship di Hellocation?,Dari mana anda mengetahui informasi mentorship ini?,Pilih kelas Mentorship yang Anda inginkan,Beasiswa apa yang ingin diikuti?,Jenjang studi yang ingin di apply?,Rencana Univ yang dituju dan jurusan,Tanggal transfer
2,7/20/2023 22:27:03,Hernio Bayuaji Hutomo,Universitas Airlangga,-,Palu,27,85713468183,Herniohoetomo,Ingin lebih tau tentang beasiswa GKS,Iklan di IG,Kelas Reguler,GKS,S2,Yonsei - Global MBA,7/20/2023
3,7/21/2023 7:57:10,Willy Yudistira,SMAN 1 Maos,IPA,"Cilacap, Jawa Tengah",18,81235324019,@willyudistira,Belajar,Postingan hellocation,Kelas Reguler,GKS,S1,-,7/21/2023
4,7/21/2023 18:38:45,YAYANG DIAZ ASTI PUTRI,SMKN 4 Malang,Rekayasa Perangkat Lunak,Malang,18 tahun,8563269623,@yayanggdiaz,Karena ingin mendaftar beasiswa GKS (Global Ko...,Dari postingan instagram @hellocation,Kelas Reguler,Beasiswa GKS (Korea Selatan),S1,Korea University - Industrial Management Engin...,7/21/2023
5,7/21/2023 20:48:07,Ericha Veonetta Siswanto,SMAK Santo Paulus,IPS,Sidoarjo,19,81339310141,erichasiswanto,Karena memiliki rencana untuk apply di GKS dan...,twitter,Kelas Reguler,GKS,S1,"Chungnam University, International trade",7/21/2023
6,7/22/2023 19:21:07,SUCI AYU LESTARI,SMAN 1 ROGOJAMPI,IPA,BANYUWANGI,18 tahun,85718081329,@acibility,Karena ingin melanjutkan S1 ke Korea Selatan m...,dari instagram Hellocationkorea,Kelas Reguler,GKS (Korea Selatan),S1,"Jeonbuk National University, jurusan Food Scie...",7/22/2023
7,7/24/2023 13:56:24,Ya Putri,Universitas Andalas,fisika,"Jl. Usman no 122, rt 08 rw 08 kelapa dua, kebo...",28,085738202603 & 085728650219,Ya Putri / @ya.putri,ingin lulus tahapan beasiswa gks,dari postingan reels intagram,Kelas Private,GKS,S2,Yonsei university dan Fisika,7/21/2023
8,8/1/2023 18:05:41,Farsya Maulida Wildani,Sman 1 Gambiran,IPS,Banyuwangi,21,85648530782,@farsyaaamm_,Looking for better guidance in applying GKS in...,Hellocation,Kelas Private,GKS,S1,SNU (priority) - English Education,8/1/2023
9,8/1/2023 19:27:23,Hanifati Azatil Ismah,Politeknik Negeri Jakarta,Business Administration - MICE & Event Management,Bogor,24,8568563453,ismahnft,Ingin mengetahui lebih banyak tentang proses a...,Instagram Hellocation,Kelas Reguler,GKS,S2,"Yonsei/Kyunghee University, Business School (MBA)",1/8/2023
10,8/7/2023 18:41:17,Qinthara Nazzala Oditha Puteri Liando,SMAN 81 Jakarta,IPA,Kota Malang,19,85714071118,qintharaaliando,Karena saya ingin mendapatkan bimbingan untuk ...,Dari ads instagram,Kelas Private,GKS-U (Korea Selatan),S1,Hanyang University/Yonsei University jurusan I...,8/7/2023
11,8/20/2023 18:59:14,Salsabiela Vitasari Jasmine,UIN Maulana Malik Ibrahim Malang,-,Bangkalan,22,85931200150,s.v._jasmine,Karena saya ingin melanjutkan S2 ke Korea mela...,Dari postingan Instagram @hellocationkorea,Kelas Reguler,GKS (Korea Selatan),S2,EWHA Womans University - S2 Medical Science,8/20/2023
12,8/21/2023 8:31:28,Nasywa Nabila Nur Shabrina,Universitas Airlangga,Psikologi,Surabaya,19,6281336669995,@nasywaanns,Ingin menambah wawasan!,Iklan instagram,Kelas Private,GKS (Korea Selatan),S2,Korea University - Counseling Psychology / Cli...,8/21/2023
13,8/24/2023 18:53:45,Nikita Larasati,Sma pgri plus cibinong,Ipa,Yogyakarta,20,87741353079,Jhxx03,Mengetahui lebih dalam GKS dan proofreading Do...,Postingan ig (lewat tl),Kelas Private,GKS,S1,Soonchuhyang Univ Information Security eng,7/28/2023
14,8/24/2023 18:54:31,Deandra Annisa Putri,Universitas Gadjah Mada,-,Surabaya,24,85156159388,deandraptri,Mau ikut seleksi GKS U 2023,Dari teman,Kelas Private,GKS,S1,Embassy Track: 1. Kangwon National University ...,6/3/2023
15,9/1/2023 15:00:53,Ignatius Loyola Revalino Chandra Kurniawan,Lulusan SMA Strada St. Thomas Aquino & sedang ...,SMA IPA & Kuliah teknik mesin,Tangerang dan Semarang,18,81315107583,@revalinochandra,Mau apply GKS 2023 dan mempersiapkan untuk bea...,Iklan hellocation di ig,Kelas Private,"GKS, MEXT, University direct scholarship, CGS,",S1,"UNSW, TiTech, Yonsei, KU Leuven, UofT, Nagoya",9/1/2023
16,9/1/2023 21:53:25,ALIFIA AZZAHRA + RIMATUL ULA,-,-,Bogor,22,85174405290,aarhazzaaifila,Mau mendaftar beasiswa GKS,instagram hellocation,Kelas Reguler,GKS,S1,Chonnam National University (Univ Track) + Y...,9/1/2023
17,9/2/2023 22:27:24,Valencia Oktaliana Ekaputri,Universitas Gadjah Mada,Ilmu Ekonomi,Yogyakarta,17 tahun,85648794349,vlncaliana,Ingin menambah insight dari para awardee yang ...,instagram Hellocation Korea,Kelas Reguler,GKS (Korea Selatan),S1,Yonsei University Jurusan Business Administration,9/2/2023
18,9/2/2023 23:56:28,Nur Zahro,IAIN SYEKH NURJATI CIREBON,-,Cirebon,19 tahun,082118272153‬,Chloeezza,Agar mendapatkan informasi tentang GKS yang je...,Dari instagram,Kelas Reguler,GKS (Korea Selatan),S1,"Korea University, Industrial Management Engine...",9/2/2023
19,9/12/2023 20:43:42,Alinia Qkhan Dinie Syaputri,SMA Negeri 6 Palembang,IPA,Palembang,17 Tahun,895326378053,@aliniaqkhann,karena mentornya merupakan awardee dari beasis...,dari akun official hellocation,Kelas Reguler,GKS,S1,"SNU Industrial Engineering, KU Industrial Engi...",9/12/2023
20,9/13/2023 12:53:48,Hasifa Zaysha Albany,SMA Labschool Cirendeu,IPA,Jakarta Selatan,17,81381475505,zayyshaa,karna berminta mendaftar di Global Korean Scho...,Tiktok,Kelas Private,GKS,S1,"Soonchunhyang University, Food Science and nut...",9/13/2023
21,9/13/2023 18:11:21,Ranya Kayla Bilqisthi,SMKS Islamic Village,- (SMK - DKV),Kota Tangerang,18,82112359623,@skezoie/@camiedrafts,Untuk mengetahui info lebih lanjut terkait GKS...,instagram @hellocation.id,Kelas Reguler,Beasiswa GKS,S1,Hanyang - DIS/International Relations,9/13/2023
22,9/13/2023 19:17:00,Syahla Audy Taqwa Nabila,Sman 1 Batujajar,Bahasa,"Bandung, Jawa Barat",19,‪+62 882‑2217‑7571‬,@syahlaudy @syahlaaudy,Untuk membantu saya dalam menyiapkan Personal ...,Telegram,Kelas Reguler,GKS (Korea Selatan),S1,Korea University - International Studies,9/13/2023
23,9/13/2023 22:37:49,Joyce audrey jaya,pelangi kasih,IPA,jakarta barat,18,81285400902,joyceeaj,ingin apply gks scholarship,instagram,Kelas Reguler,GKS,S1,blm fix” bgt hehe,9/13/2023
24,9/13/2023 23:43:44,Irene Angelia Hartono,Lulusan Smak Kesuma mataram,Lulusan IPA,Surabaya,18,81805244210,ireneah,Ingin daftar gks,Tiktok,Kelas Reguler,Gks,S1,"SKY , computer science",9/13/2023
25,9/15/2023 12:01:31,Amelia Wahyuningtyas,SMAN 4 KISARAN,SMA (KURIKULUM MERDEKA) IPA,"Kisaran, Sumatra Utara",17,83186690665,amltysz_,alasan saya mengikuti hellocation adalah untuk...,@infowebinar.id,Kelas Reguler,GKS (KOREA SELATAN),S1,"Yonsei, SNU, Sungkyunkwan, Ewha, Hanyang, Konk...",9/15/2023
26,9/15/2023 15:04:11,FINTI,SMKN 1 Mempawah Hilir,Akuntasi,Alamat jln Raya pasar semudun kab. Mempawah ...,21 Tahun,87847529982,Fintyclarita_,Dikarenakan ingin dapat bimbingan yang lebih s...,Dafi postingan instagram @hellocationkorea,Kelas Private,GKS,S1,"Yonsei university, SNU, KU, dan Ewha University",9/15/2023
27,9/15/2023 20:35:09,Tiara Sagita,Universiti Pendidikan Sultan Idris,Science,Batam,22,82170367591,tiaeraa,bimbingan dan proofread essay,postingan septi khairullah,Kelas Reguler,GKS,S1,Korea University - Biotechnology,9/15/2023
28,9/20/2023 10:50:14,Indira Maia Banaati,PMD Gontor Putri Kampus 3,Non jurusan,"Gunung Putri, Kab. Bogor",19 Tahun,85770937661,indira_bntie05,Agar bisa lebih siap dan matang dalam mempersi...,Dari iklan instagram,Kelas Private,GKS (Korea Selatan),S1,Medicine division,9/20/2023
29,9/22/2023 12:14:10,Jennifer Sanjean,Kalam Kudus,IPA,Sumatera Utara,17,85100067737,Me_10_09,-,Instagram,Kelas Private,GKS,S1,Snu - berhubungan dengan IPA,9/21/2023

In [100]:
gks_g.dropna()

,Timestamp,Nama Lengkap,Asal Instansi,Jurusan,Domisili,Umur,No. HP aktif,Nama akun instagram,Alasan ingin mengikuti mentorship,Pilih kelas Mentorship yang Anda inginkan
1,04/01/2023 20:17:26,Mauliandini Nur Noviasri,Universitas Brawijaya,Perencanaan Wilayah dan Kota,Jakarta,36,81908200974,mauliandininoviasri,Rencana melanjutkan pendidikan S2 melalui beas...,Kelas Reguler
2,04/01/2023 21:01:02,Nabila Putri Candisa,Universitas Prasetiya Mulya,Marketing,Tangerang,28,85720368532,ncandisa,Ingin mendaftar GKS-G dan butuh mentorship ser...,Kelas Private
3,05/01/2023 14:02:34,Luchia Pri Utama,Universitas Bakrie,Hubungan Internasional,Jakarta,26,87766383553,luchiaerina,Persiapan untuk daftar GKS 2023,Kelas Reguler
4,08/01/2023 22:46:41,Elisabet Suryani Wianto,Universitas Trisakti,Akuntansi,Semarang,25,83838959450,elisabetsw_,Tahun ini baru pertama kali mau coba daftar GK...,Kelas Private
5,12/01/2023 17:17:53,Luisa Tiara Purnomo,Monash University,Media Communications,"BSD, Tangerang Selatan",21,81219550302,luisa_tiara,Persiapan daftar GKS 2023,Kelas Reguler
6,16/01/2023 20:14:00,Hasna Karimah,ITB,Magister Informatika,Bandung,23,08966776860q,karimahasna.prntdst,ingin melanjutkan pendidikan doktoral di KAIST...,Kelas Reguler
7,21/01/2023 18:15:20,Elfrida Dwiyanti,Universitas Indonesia,Ilmu Komunikasi,"Busan, Korea Selatan",25,8811209009,elfridadwi,Saya ingin lolos beasiswa GKS thn 2023. Walaup...,Kelas Private
8,21/01/2023 21:33:58,Zulfahmi Sukma,Universitas Tanjungpura,Kehutanan,Kalimantan Barat,21,81256779403,zulfahmizulfagyd_200102,Untuk persiapan apply beasiswa GKS \nBismillah,Kelas Reguler
9,22/01/2023 13:50:53,-,-,-,-,-,-,-,-,Kelas Reguler
10,24/01/2023 22:47:41,Putrini Andrea Zebua,Universitas Prasetiya Mulya,Branding,Tangerang Selatan,21 tahun,81932329213,dea.zebua,Ingin tahu lebih mengenai beasiswa ke Korea,Kelas Reguler
11,25/01/2023 16:21:50,Nur Anisa Kurnia Putri,Universitas Hang Tuah Surabaya,Pendidikan Profesi Dokter Gigi,Surabaya,24,81299067974,nuranisakputri,mempersiapkan GKS-G 2023,Kelas Private
12,26/01/2023 10:59:40,Sekar ratri,Universitas Negeri Surabaya,_,Tangerang,37,85776227118,sekararatri_02,Bisa studi master di korea n level up karir,Kelas Reguler
13,26/01/2023 17:07:22,Ervani Tri Wijayanti,STIE Indonesia Banking School,Manajemen,Depok,22,81287119743,ervanit,"InsyaAllah jadi salah satu awardee GKS-G 2023,...",Kelas Private
14,28/01/2023 10:29:08,Nurti Hutagalung,0,0,Jakarta Selatan,0,82304622216,Nurti,Sedang mencari beasiswa ke Korea Selatan,Kelas Reguler
15,28/01/2023 12:04:40,Ismi Afifah,Universitas Jember,Perencanaan Wilayah dan Kota,Probolinggo,22,82334128218,ismiafifaa,karena ingin lebih memahami tentang step by st...,Kelas Reguler
16,28/01/2023 16:29:15,Ulfiani Fauzia Hanafi,Universitas Airlangga,-,Tangerang selatan,23,81272863581,ulfianifh,Ingin mendaftar GKS dan masih bingung dalam me...,Kelas Private
17,28/01/2023 16:58:22,Sari Intan Romauli,Universitas Mikroskil,Manajemen Bisnis,Medan,23,895611078810,sariintan.61,Ingin mendaftar GKS ditahun 2023,Kelas Reguler
18,28/01/2023 19:50:05,Apsari Noor Eka Ramadhanty,UPN “Veteran” Yogyakarta,-,Yogyakarta,24,85720225369,kkulloves,ingin mempersiapkan untuk GKS 2023,Kelas Reguler
19,28/01/2023 20:42:37,Sisma Faoziah,Institut Agama Islam Negeri (IAIN) Syekh Nurja...,Perbankan Syariah,Cirebon,25,81252788470,@jiaaaaa.xi,Membutuhkan mentor agar persyaratan nya bisa d...,Kelas Private
20,30/01/2023 14:30:03,Fairuz Nabila,Universitas Negeri Jakarta,-,Tangerang,25,82299094845,faairuznabila,Ingin dibantu persiapan beasiswa GKS mulai dar...,Kelas Private
21,08/02/2023 17:58:06,Farhata Atqiya,Yarsi,Gizi,Padang,18,6282288796198,taaqiiyyaa_,"Ingin mendapatkan pengayoman,bimbingan, arahan...",Kelas Private
22,19/02/2023 23:00:22,Syammas Pinasthika Syarbini,Esa Unggul,Marketing Communication,Bekasi,27,81258520463,@syammasfitria,Untuk beasiswa S2 Komunikasi,Kelas Reguler
24,26/02/2023 12:02:40,Aisyah Yasmin,Telkom University,Design Produk,Tangerang Selatan,24 thn,81212369655,yasmiinaisya,persiapan untuk gks 2023 university track,Kelas Private
25,27/02/2023 16:37:18,INTAN GITA LESTARI,Universitas Diponegoro,Kimia,"Pati, Jawa Tengah",22,82235404217,i_ntangita,untuk persiapan pendaftaran gks graduate agar ...,Kelas Reguler
26,28/02/2023 23:07:17,Erma Kusumawardani,Universitas Negeri Yogyakarta,Pendidikan Nonformal,Yogyakarta,28,85728268800,ermaksma,Ingin didampingi dari penyiapan hingga submit,Kelas Private
27,02/03/2023 15:19:26,William Shakespeare,Universitas Negeri Makassar,-,Cambodia,27,85333055318,Shaakespeareee,Ingin dibimbing dan bertemu dgn mentor yang lu...,Kelas Private
28,02/03/2023 17:50:51,Damaa Pandya,UGM,Manajemen,Yogyakarta,24,87839395557,damaspandya,Ingib mengetahui experience secara mendalam de...,Kelas Reguler
29,03/03/2023 11:11:35,Yessica Ryanti Anggajaya,Universitas Mataram,Ilmu Komunikasi,Lombok,22,81339879390,Yessicaaang,Mempersiapkan diri untuk pendaftaran GKS tahun...,Kelas Reguler
30,03/03/2023 21:20:29,Januika Setiyawanti,Universitas Teknologi Yogyakarta,S1-Akuntansi,Yogyakarta,29,81328108659,januika_setiyawanti,Mau apply GKS-G tahun ini jalur univ,Kelas Reguler
31,03/03/2023 22:59:51,Umi Nur Safitri,Universitas Diponegoro,Perikanan,Batang,25,85226496128,@umaaaisf,Persiapan pendaftaran gks,Kelas Reguler
32,04/03/2023 13:12:34,Apsari Noor Eka R,UPN “Veteran” Yogyakarta,-,Yogya,24,85720225369,kkulloves,mencari informasi,Kelas Reguler - Pertemuan 1
33,04/03/2023 20:12:59,Joselyn Alexandra Antolim,SMA Santa Laurensia Alam Sutera,SMA menggunakan kurikulum pearson edexcel sehi...,Tangerang Selatan,17,85388893689,joselyn.alexandra_,Untuk mempersiapkan pendaftaran universitas,Kelas Private
34,07/03/2023 12:36:28,Ely Yosriah,IAIN Syekh Nurjati Cirebon,Pendidikan Biologi (S1),Cirebon,25,82119392052,-,Mendapat feedback essay,Kelas Reguler - Pertemuan 4
35,13/03/2023 22:07:59,Indah Permatasari,Universitas Pendidikan Indonesia,Manajemen,Bandung,25,81221906743,@inddps,Ingin mendaftar GKS,Kelas Reguler - Pertemuan 4
36,23/03/2023 12:54:40,Tasya Angelita,UNS,Sastra Indonesia,Solo,21,81267008357,tasyaangelitaa,Ingin,Kelas Reguler
37,28/07/2023 19:39:52,Nikita Larasati,SMA PGRI Cibinong,IPA,Yogyakarta,20,87741353079,jhxx03,Agar persiapan scholarship lebih matang,Kelas Private
38,21/08/2023 2:22:25,Karina Nathania Gunawan,Universitas Widya Mandala Surabaya,Kedokteran,"Jombang, Jawa Timur",26,82234181771,@karina_nathania,Ingin S2 di Korea,Kelas Reguler

In [101]:
gks_sheet.dropna()

Empty DataFrame
Columns: [Timestamp, Nama Lengkap, Asal Instansi, Jurusan, Domisili, Umur, No. HP aktif, Nama akun instagram, Alasan ingin mengikuti mentorship, Pilihan Kelas, Apakah kamu bersedia melakukan pembayaran sebesar Rp200.000 untuk kelas Reguler?, Apakah kamu bersedia menghadiri Onboarding yang akan dilaksanakan pada tanggal 6 Agustus 2022?, Apakah kamu bersedia mengikuti mentorship pada tanggal yang sudah ditentukan?, Unnamed: 13, Unnamed: 14, Unnamed: 15]
Index: []

#Cek Dataset

In [102]:
gks_u.describe(include='all')

,Timestamp,Nama Lengkap,Asal Instansi,Jurusan,Domisili,Umur,No. HP aktif,Nama Acc Instagram,Alasan mengikuti mentorship di Hellocation?,Dari mana anda mengetahui informasi mentorship ini?,Pilih kelas Mentorship yang Anda inginkan,Beasiswa apa yang ingin diikuti?,Jenjang studi yang ingin di apply?,Rencana Univ yang dituju dan jurusan,Tanggal transfer
count,30,30,30,30,30,30,30,30,30,30,30,30,30,28,30
unique,30,30,28,18,26,15,30,30,30,29,2,8,2,28,19
top,7/13/2023 21:11:01,rima,Universitas Airlangga,IPA,Surabaya,18,82397070770,-,mau persiapan ikut gks,Tiktok,Kelas Reguler,GKS,S1,Yonsei - Global MBA,9/13/2023
freq,1,1,2,7,3,6,1,1,1,2,17,15,25,1,5

In [103]:
gks_g.describe(include='all')

,Timestamp,Nama Lengkap,Asal Instansi,Jurusan,Domisili,Umur,No. HP aktif,Nama akun instagram,Alasan ingin mengikuti mentorship,Pilih kelas Mentorship yang Anda inginkan
count,38,38,38,38,38,38,38,38,38,37
unique,38,38,35,28,27,18,37,36,38,4
top,12/12/2022 21:25:50,Nurhalija,UPN “Veteran” Yogyakarta,-,Yogyakarta,25,85720225369,kkulloves,Ingin dibimbing dalam mempersiapkan diri utk m...,Kelas Reguler
freq,1,1,2,6,5,7,2,2,1,20

In [104]:
gks_sheet.describe(include='all')

,Timestamp,Nama Lengkap,Asal Instansi,Jurusan,Domisili,Umur,No. HP aktif,Nama akun instagram,Alasan ingin mengikuti mentorship,Pilihan Kelas,Apakah kamu bersedia melakukan pembayaran sebesar Rp200.000 untuk kelas Reguler?,Apakah kamu bersedia menghadiri Onboarding yang akan dilaksanakan pada tanggal 6 Agustus 2022?,Apakah kamu bersedia mengikuti mentorship pada tanggal yang sudah ditentukan?,Unnamed: 13,Unnamed: 14,Unnamed: 15
count,42,42,42,42,42,42,42,42,42,32,42,42,42,0.0,0.0,3
unique,42,42,42,25,33,16,42,42,42,2,2,6,2,NaN,NaN,3
top,29/07/2022 12:19:37,Alexandra,SMK Analis Kimia Bogor,IPA,Bogor,19,81514090657,alexa.drrr,Alasan saya mengikuti program mentorship adala...,Reguler,Ya,Ya,Ya,NaN,NaN,*Peserta tidak jelas
freq,1,1,1,10,3,10,1,1,1,23,38,37,41,NaN,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
#cek data null
print('\nData Null GKS U:\n', gks_u.isnull().sum())
print('\nData Null GKS G:\n', gks_g.isnull().sum())
print('\nData Null GKS Sheet:\n', gks_sheet.isnull().sum())

Data Null GKS U:
 Timestamp                                              0
Nama Lengkap                                           0
Asal Instansi                                          0
Jurusan                                                0
Domisili                                               0
Umur                                                   0
No. HP aktif                                           0
Nama Acc Instagram                                     0
Alasan mengikuti mentorship di Hellocation?            0
Dari mana anda mengetahui informasi mentorship ini?    0
Pilih kelas Mentorship yang Anda inginkan              0
Beasiswa apa yang ingin diikuti?                       0
Jenjang studi yang ingin di apply?                     0
Rencana Univ yang dituju dan jurusan                   2
Tanggal transfer                                       0
dtype: int64

Data Null GKS G:
 Timestamp                                    1
Nama Lengkap                                 1
Asal Instansi                                1
Jurusan                                      1
Domisili                                     1
Umur                                         1
No. HP aktif                                 1
Nama akun instagram                          1
Alasan ingin mengikuti mentorship            1
Pilih kelas Mentorship yang Anda inginkan    2
dtype: int64

Data Null GKS Sheet:
 Timestamp                                                                                          0
Nama Lengkap                                                                                       0
Asal Instansi                                                                                      0
Jurusan                                                                                            0
Domisili                                                                                           0
Umur                                                                                               0
No. HP aktif                                                                                       0
Nama akun instagram                                                                                0
Alasan ingin mengikuti mentorship                                                                  0
Pilihan Kelas                                                                                     10
Apakah kamu bersedia melakukan pembayaran sebesar Rp200.000 untuk kelas Reguler?                   0
Apakah kamu bersedia menghadiri Onboarding yang akan dilaksanakan pada tanggal 6 Agustus 2022?     0
Apakah kamu bersedia mengikuti mentorship pada tanggal yang sudah ditentukan?                      0
Unnamed: 13                                                                                       42
Unnamed: 14                                                                                       42
Unnamed: 15                                                                                       39
dtype: int64

In [106]:
#cek data duplikat
print('\nData Duplikat GKS U:\n', gks_u.duplicated().sum())
print('\nData Duplikat GKS G:\n', gks_g.duplicated().sum())
print('\nData Duplikat GKS Sheet:\n', gks_sheet.duplicated().sum())

Data Duplikat GKS U:
 0

Data Duplikat GKS G:
 0

Data Duplikat GKS Sheet:
 0

#Cleaning Data

###Ubah semua judul kolom jadi huruf kecil

In [109]:
# Ganti nama kolom menjadi huruf kecil dan bersambung, dan menghapus tanda tanya
gks_u.columns = [remove_question_marks(col.lower().replace(' ', '_')) for col in gks_u.columns]

kolom_yang_dihapus = 'judul_kolom_yang_sangat_panjang'
if kolom_yang_dihapus in gks_u.columns:
    gks_u.drop(columns=kolom_yang_dihapus, inplace=True)

def remove_question_marks_from_data(text):
    if isinstance(text, str):
        return re.sub(r'[?]', '', text)
    return text

gks_u.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   timestamp                                           30 non-null     object
 1   nama_lengkap                                        30 non-null     object
 2   asal_instansi                                       30 non-null     object
 3   jurusan                                             30 non-null     object
 4   domisili                                            30 non-null     object
 5   umur                                                30 non-null     object
 6   no._hp_aktif                                        30 non-null     object
 7   nama_acc_instagram                                  30 non-null     object
 8   alasan_mengikuti_mentorship_di_hellocation          30 non-null     object
 9   dari_mana_anda_mengetahui_informasi_mentorship_ini  30 non-null     object
 10  pilih_kelas_mentorship_yang_anda_inginkan           30 non-null     object
 11  beasiswa_apa_yang_ingin_diikuti                     30 non-null     object
 12  jenjang_studi_yang_ingin_di_apply                   30 non-null     object
 13  rencana_univ_yang_dituju_dan_jurusan                28 non-null     object
 14  tanggal_transfer                                    30 non-null     object
dtypes: object(15)
memory usage: 3.6+ KB

In [110]:
# Ganti nama kolom menjadi huruf kecil dan bersambung, dan menghapus tanda tanya
gks_g.columns = [remove_question_marks(col.lower().replace(' ', '_')) for col in gks_g.columns]

kolom_yang_dihapus = 'judul_kolom_yang_sangat_panjang'
if kolom_yang_dihapus in gks_g.columns:
    gks_g.drop(columns=kolom_yang_dihapus, inplace=True)

def remove_question_marks_from_data(text):
    if isinstance(text, str):
        return re.sub(r'[?]', '', text)
    return text

gks_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 10 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   timestamp                                  38 non-null     object
 1   nama_lengkap                               38 non-null     object
 2   asal_instansi                              38 non-null     object
 3   jurusan                                    38 non-null     object
 4   domisili                                   38 non-null     object
 5   umur                                       38 non-null     object
 6   no._hp_aktif                               38 non-null     object
 7   nama_akun_instagram                        38 non-null     object
 8   alasan_ingin_mengikuti_mentorship          38 non-null     object
 9   pilih_kelas_mentorship_yang_anda_inginkan  37 non-null     object
dtypes: object(10)
memory usage: 3.2+ KB

In [111]:
gks_sheet.columns = [remove_question_marks(col.lower().replace(' ', '_')) for col in gks_sheet.columns]

kolom_yang_dihapus = 'judul_kolom_yang_sangat_panjang'
if kolom_yang_dihapus in gks_sheet.columns:
    gks_sheet.drop(columns=kolom_yang_dihapus, inplace=True)

def remove_question_marks_from_data(text):
    if isinstance(text, str):
        return re.sub(r'[?]', '', text)
    return text

gks_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 16 columns):
 #   Column                                                                                         Non-Null Count  Dtype
---  ------                                                                                         --------------  -----
 0   timestamp                                                                                      42 non-null     object
 1   nama_lengkap                                                                                   42 non-null     object
 2   asal_instansi                                                                                  42 non-null     object
 3   jurusan                                                                                        42 non-null     object
 4   domisili                                                                                       42 non-null     object
 5   umur                                                                                           42 non-null     object
 6   no._hp_aktif                                                                                   42 non-null     object
 7   nama_akun_instagram                                                                            42 non-null     object
 8   alasan_ingin_mengikuti_mentorship                                                              42 non-null     object
 9   pilihan_kelas                                                                                  32 non-null     object
 10  apakah_kamu_bersedia_melakukan_pembayaran_sebesar_rp200.000_untuk_kelas_reguler                42 non-null     object
 11  apakah_kamu_bersedia_menghadiri_onboarding_yang_akan_dilaksanakan_pada_tanggal_6_agustus_2022  42 non-null     object
 12  apakah_kamu_bersedia_mengikuti_mentorship_pada_tanggal_yang_sudah_ditentukan                   42 non-null     object
 13  unnamed:_13                                                                                    0 non-null      float64
 14  unnamed:_14                                                                                    0 non-null      float64
 15  unnamed:_15                                                                                    3 non-null      object
dtypes: float64(2), object(14)
memory usage: 5.4+ KB

In [116]:
gks_sheet = gks_sheet.drop(columns=['unnamed:_14'])
gks_sheet = gks_sheet.drop(columns=['unnamed:_15'])

In [117]:
gks_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 13 columns):
 #   Column                                                                                         Non-Null Count  Dtype
---  ------                                                                                         --------------  -----
 0   timestamp                                                                                      42 non-null     object
 1   nama_lengkap                                                                                   42 non-null     object
 2   asal_instansi                                                                                  42 non-null     object
 3   jurusan                                                                                        42 non-null     object
 4   domisili                                                                                       42 non-null     object
 5   umur                                                                                           42 non-null     object
 6   no._hp_aktif                                                                                   42 non-null     object
 7   nama_akun_instagram                                                                            42 non-null     object
 8   alasan_ingin_mengikuti_mentorship                                                              42 non-null     object
 9   pilihan_kelas                                                                                  32 non-null     object
 10  apakah_kamu_bersedia_melakukan_pembayaran_sebesar_rp200.000_untuk_kelas_reguler                42 non-null     object
 11  apakah_kamu_bersedia_menghadiri_onboarding_yang_akan_dilaksanakan_pada_tanggal_6_agustus_2022  42 non-null     object
 12  apakah_kamu_bersedia_mengikuti_mentorship_pada_tanggal_yang_sudah_ditentukan                   42 non-null     object
dtypes: object(13)
memory usage: 4.4+ KB

#EDA (Exploratory Data Analysis)

##Explore gks_u

In [118]:
gks_u.sample(5)

,timestamp,nama_lengkap,asal_instansi,jurusan,domisili,umur,no._hp_aktif,nama_acc_instagram,alasan_mengikuti_mentorship_di_hellocation,dari_mana_anda_mengetahui_informasi_mentorship_ini,pilih_kelas_mentorship_yang_anda_inginkan,beasiswa_apa_yang_ingin_diikuti,jenjang_studi_yang_ingin_di_apply,rencana_univ_yang_dituju_dan_jurusan,tanggal_transfer
24,9/13/2023 23:43:44,Irene Angelia Hartono,Lulusan Smak Kesuma mataram,Lulusan IPA,Surabaya,18,81805244210,ireneah,Ingin daftar gks,Tiktok,Kelas Reguler,Gks,S1,"SKY , computer science",9/13/2023
1,7/15/2023 17:37:03,Adriana Salsabila Irawan,SMAN 4 SUBANG,IPS,Buana Subang Kencana blok F64 RT.48 RW.16 Sokl...,18,87822380897,@adrianaaiss,butuh bimbingan beasiswa gks,dari tiktok hellocation,Kelas Private,GKS (Korea Selatan),S1,NaN,7/15/2023
21,9/13/2023 18:11:21,Ranya Kayla Bilqisthi,SMKS Islamic Village,- (SMK - DKV),Kota Tangerang,18,82112359623,@skezoie/@camiedrafts,Untuk mengetahui info lebih lanjut terkait GKS...,instagram @hellocation.id,Kelas Reguler,Beasiswa GKS,S1,Hanyang - DIS/International Relations,9/13/2023
5,7/21/2023 20:48:07,Ericha Veonetta Siswanto,SMAK Santo Paulus,IPS,Sidoarjo,19,81339310141,erichasiswanto,Karena memiliki rencana untuk apply di GKS dan...,twitter,Kelas Reguler,GKS,S1,"Chungnam University, International trade",7/21/2023
10,8/7/2023 18:41:17,Qinthara Nazzala Oditha Puteri Liando,SMAN 81 Jakarta,IPA,Kota Malang,19,85714071118,qintharaaliando,Karena saya ingin mendapatkan bimbingan untuk ...,Dari ads instagram,Kelas Private,GKS-U (Korea Selatan),S1,Hanyang University/Yonsei University jurusan I...,8/7/2023

In [119]:
gks_u.describe(include='all')

,timestamp,nama_lengkap,asal_instansi,jurusan,domisili,umur,no._hp_aktif,nama_acc_instagram,alasan_mengikuti_mentorship_di_hellocation,dari_mana_anda_mengetahui_informasi_mentorship_ini,pilih_kelas_mentorship_yang_anda_inginkan,beasiswa_apa_yang_ingin_diikuti,jenjang_studi_yang_ingin_di_apply,rencana_univ_yang_dituju_dan_jurusan,tanggal_transfer
count,30,30,30,30,30,30,30,30,30,30,30,30,30,28,30
unique,30,30,28,18,26,15,30,30,30,29,2,8,2,28,19
top,7/13/2023 21:11:01,rima,Universitas Airlangga,IPA,Surabaya,18,82397070770,-,mau persiapan ikut gks,Tiktok,Kelas Reguler,GKS,S1,Yonsei - Global MBA,9/13/2023
freq,1,1,2,7,3,6,1,1,1,2,17,15,25,1,5

In [121]:
gks_u.timestamp.is_unique

True

In [122]:
gks_u = gks_u.rename(columns={'no._hp_aktif': 'nomor_hp'})
gks_u = gks_u.rename(columns={'nama_acc_instagram': 'nama_ig'})
gks_u = gks_u.rename(columns={'alasan_mengikuti_mentorship_di_hellocation': 'alasan_join'})

gks_u = gks_u.rename(columns={'dari_mana_anda_mengetahui_informasi_mentorship_ini ': 'info_dari'})
gks_u = gks_u.rename(columns={'pilih_kelas_mentorship_yang_anda_inginkan': 'pilih_kelas'})
gks_u = gks_u.rename(columns={'beasiswa_apa_yang_ingin_diikuti': 'beasiswa_pilihan'})
gks_u = gks_u.rename(columns={'jenjang_studi_yang_ingin_di_apply': 'apply_study'})
gks_u = gks_u.rename(columns={'rencana_univ_yang_dituju_dan_jurusan': 'univ_tujuan'})

In [124]:
gks_u = gks_u.rename(columns={'dari_mana_anda_mengetahui_informasi_mentorship_ini': 'info_dari'})

gks_u.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         30 non-null     object
 1   nama_lengkap      30 non-null     object
 2   asal_instansi     30 non-null     object
 3   jurusan           30 non-null     object
 4   domisili          30 non-null     object
 5   umur              30 non-null     object
 6   nomor_hp          30 non-null     object
 7   nama_ig           30 non-null     object
 8   alasan_join       30 non-null     object
 9   info_dari         30 non-null     object
 10  pilih_kelas       30 non-null     object
 11  beasiswa_pilihan  30 non-null     object
 12  apply_study       30 non-null     object
 13  univ_tujuan       28 non-null     object
 14  tanggal_transfer  30 non-null     object
dtypes: object(15)
memory usage: 3.6+ KB

In [127]:
gks_u["timestamp"] = pd.to_datetime(gks_u["timestamp"])

gks_u["nama_lengkap"] = gks_u["nama_lengkap"].str.title()

gks_u["asal_instansi"] = gks_u["asal_instansi"].str.title()
gks_u["asal_instansi"] = gks_u["asal_instansi"].str.replace("-", "", regex=False)
gks_u.dropna(subset=["asal_instansi"], inplace=True)

gks_u["jurusan"] = gks_u["jurusan"].str.replace("-", "", regex=False)
gks_u.dropna(subset=["jurusan"], inplace=True)

gks_u["umur"] = gks_u["umur"].astype(str)
gks_u["umur"] = gks_u["umur"].str.replace("T", " ")

gks_u["domisili"] = gks_u["domisili"].str.title()


gks_u["alasan_join"] = gks_u["alasan_join"].str.title()
gks_u["alasan_join"] = gks_u["alasan_join"].str.replace("-", "", regex=False)
gks_u.dropna(subset=["alasan_join"], inplace=True)

gks_u["info_dari"] = gks_u["info_dari"].str.title()
gks_u["info_dari"] = gks_u["info_dari"].str.replace("-", "", regex=False)
gks_u.dropna(subset=["info_dari"], inplace=True)

gks_u.loc[gks_u["pilih_kelas"] == 0, "pilih_kelas"] = "Kelas Private"
gks_u.loc[gks_u["pilih_kelas"] == 1, "pilih_kelas"] = "Kelas Reguler"

gks_u["tanggal_transfer"] = pd.to_datetime(gks_u["tanggal_transfer"])

In [128]:
gks_u.nama_lengkap.value_counts().sort_index()

Adriana Salsabila Irawan                      1
Alifia Azzahra  +   Rimatul Ula               1
Alinia Qkhan Dinie Syaputri                   1
Amelia Wahyuningtyas                          1
Deandra Annisa Putri                          1
Ericha Veonetta Siswanto                      1
Farsya Maulida Wildani                        1
Finti                                         1
Hanifati Azatil Ismah                         1
Hasifa Zaysha Albany                          1
Hernio Bayuaji Hutomo                         1
Ignatius Loyola Revalino Chandra Kurniawan    1
Indira Maia Banaati                           1
Irene Angelia Hartono                         1
Jennifer Sanjean                              1
Joyce Audrey Jaya                             1
Nasywa Nabila Nur Shabrina                    1
Nikita Larasati                               1
Nur Zahro                                     1
Qinthara Nazzala Oditha Puteri Liando         1
Ranya Kayla Bilqisthi                         1
Rima                                          1
Salsabiela Vitasari Jasmine                   1
Suci Ayu Lestari                              1
Syahla Audy Taqwa Nabila                      1
Tiara Sagita                                  1
Valencia Oktaliana Ekaputri                   1
Willy Yudistira                               1
Ya Putri                                      1
Yayang Diaz Asti Putri                        1
Name: nama_lengkap, dtype: int64

In [134]:
gks_u["umur"] = gks_u["umur"].astype(str)
gks_u["umur"] = gks_u["umur"].str.replace("ahun", " ")

gks_u.umur.value_counts().sort_index()

17       3
17       2
18       6
18       2
19       5
19       2
20       1
21       1
21       1
22       3
24       2
27       1
28       1
Name: umur, dtype: int64

In [135]:
gks_u["umur"] = gks_u["umur"].astype(int)
gks_u.umur.value_counts().sort_index()

17    5
18    8
19    7
20    1
21    2
22    3
24    2
27    1
28    1
Name: umur, dtype: int64

In [136]:
gks_u.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         30 non-null     datetime64[ns]
 1   nama_lengkap      30 non-null     object
 2   asal_instansi     30 non-null     object
 3   jurusan           30 non-null     object
 4   domisili          30 non-null     object
 5   umur              30 non-null     int64
 6   nomor_hp          30 non-null     object
 7   nama_ig           30 non-null     object
 8   alasan_join       30 non-null     object
 9   info_dari         30 non-null     object
 10  pilih_kelas       30 non-null     object
 11  beasiswa_pilihan  30 non-null     object
 12  apply_study       30 non-null     object
 13  univ_tujuan       28 non-null     object
 14  tanggal_transfer  30 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(12)
memory usage: 3.6+ KB

In [137]:
gks_u.to_csv('datacleaning_gksu.csv', index=False)

##Explore gks_g

In [138]:
gks_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 10 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   timestamp                                  38 non-null     object
 1   nama_lengkap                               38 non-null     object
 2   asal_instansi                              38 non-null     object
 3   jurusan                                    38 non-null     object
 4   domisili                                   38 non-null     object
 5   umur                                       38 non-null     object
 6   no._hp_aktif                               38 non-null     object
 7   nama_akun_instagram                        38 non-null     object
 8   alasan_ingin_mengikuti_mentorship          38 non-null     object
 9   pilih_kelas_mentorship_yang_anda_inginkan  37 non-null     object
dtypes: object(10)
memory usage: 3.2+ KB

In [139]:
gks_g = gks_g.rename(columns={'no._hp_aktif': 'nomor_hp'})
gks_g = gks_g.rename(columns={'nama_akun_instagram': 'nama_ig'})
gks_g = gks_g.rename(columns={'alasan_mengikuti_mentorship': 'alasan_join'})
gks_g = gks_g.rename(columns={'pilih_kelas_mentorship_yang_anda_inginkan': 'pilih_kelas'})

gks_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   timestamp                          38 non-null     object
 1   nama_lengkap                       38 non-null     object
 2   asal_instansi                      38 non-null     object
 3   jurusan                            38 non-null     object
 4   domisili                           38 non-null     object
 5   umur                               38 non-null     object
 6   nomor_hp                           38 non-null     object
 7   nama_ig                            38 non-null     object
 8   alasan_ingin_mengikuti_mentorship  38 non-null     object
 9   pilih_kelas                        37 non-null     object
dtypes: object(10)
memory usage: 3.2+ KB

In [140]:
gks_g = gks_g.rename(columns={'alasan_ingin_mengikuti_mentorship': 'alasan_join'})

gks_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      38 non-null     object
 1   nama_lengkap   38 non-null     object
 2   asal_instansi  38 non-null     object
 3   jurusan        38 non-null     object
 4   domisili       38 non-null     object
 5   umur           38 non-null     object
 6   nomor_hp       38 non-null     object
 7   nama_ig        38 non-null     object
 8   alasan_join    38 non-null     object
 9   pilih_kelas    37 non-null     object
dtypes: object(10)
memory usage: 3.2+ KB

In [141]:
gks_g["timestamp"] = pd.to_datetime(gks_g["timestamp"])

gks_g["nama_lengkap"] = gks_g["nama_lengkap"].str.title()

gks_g["asal_instansi"] = gks_g["asal_instansi"].str.title()
gks_g["asal_instansi"] = gks_g["asal_instansi"].str.replace("-", "", regex=False)
gks_g.dropna(subset=["asal_instansi"], inplace=True)

gks_g["jurusan"] = gks_g["jurusan"].str.replace("-", "", regex=False)
gks_g.dropna(subset=["jurusan"], inplace=True)

gks_g["umur"] = gks_g["umur"].astype(str)
gks_g["umur"] = gks_g["umur"].str.replace("T", " ")

gks_g["domisili"] = gks_g["domisili"].str.title()

gks_g["alasan_join"] = gks_g["alasan_join"].str.replace("-", "", regex=False)
gks_g.dropna(subset=["alasan_join"], inplace=True)


gks_g.loc[gks_g["pilih_kelas"] == 0, "pilih_kelas"] = "Kelas Private"
gks_g.loc[gks_g["pilih_kelas"] == 1, "pilih_kelas"] = "Kelas Reguler"

In [142]:
gks_u["umur"] = gks_u["umur"].astype(str)
gks_u["umur"] = gks_u["umur"].str.replace("ahun", " ")

gks_u.umur.value_counts().sort_index()

17    5
18    8
19    7
20    1
21    2
22    3
24    2
27    1
28    1
Name: umur, dtype: int64

In [143]:
gks_g["umur"] = gks_u["umur"].astype(int)

gks_g.umur.value_counts().sort_index()

17.0    5
18.0    7
19.0    7
20.0    1
21.0    2
22.0    3
24.0    2
27.0    1
28.0    1
Name: umur, dtype: int64

In [144]:
gks_g.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38 entries, 0 to 38
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      38 non-null     datetime64[ns]
 1   nama_lengkap   38 non-null     object
 2   asal_instansi  38 non-null     object
 3   jurusan        38 non-null     object
 4   domisili       38 non-null     object
 5   umur           29 non-null     float64
 6   nomor_hp       38 non-null     object
 7   nama_ig        38 non-null     object
 8   alasan_join    38 non-null     object
 9   pilih_kelas    37 non-null     object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 3.3+ KB

In [151]:
gks_g["umur"] = gks_u["umur"].astype(str)
gks_g.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38 entries, 0 to 38
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      38 non-null     datetime64[ns]
 1   nama_lengkap   38 non-null     object
 2   asal_instansi  38 non-null     object
 3   jurusan        38 non-null     object
 4   domisili       38 non-null     object
 5   umur           29 non-null     object
 6   nomor_hp       38 non-null     object
 7   nama_ig        38 non-null     object
 8   alasan_join    38 non-null     object
 9   pilih_kelas    37 non-null     object
dtypes: datetime64[ns](1), object(9)
memory usage: 3.3+ KB

In [152]:
gks_g["umur"] = gks_u["umur"].astype(int)
gks_g.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38 entries, 0 to 38
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      38 non-null     datetime64[ns]
 1   nama_lengkap   38 non-null     object
 2   asal_instansi  38 non-null     object
 3   jurusan        38 non-null     object
 4   domisili       38 non-null     object
 5   umur           29 non-null     float64
 6   nomor_hp       38 non-null     object
 7   nama_ig        38 non-null     object
 8   alasan_join    38 non-null     object
 9   pilih_kelas    37 non-null     object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 3.3+ KB

In [153]:
gks_g.sample(5)

,timestamp,nama_lengkap,asal_instansi,jurusan,domisili,umur,nomor_hp,nama_ig,alasan_join,pilih_kelas
24,2023-02-26 12:02:40,Aisyah Yasmin,Telkom University,Design Produk,Tangerang Selatan,18.0,81212369655,yasmiinaisya,Persiapan Untuk Gks 2023 University Track,Kelas Private
38,2023-08-21 02:22:25,Karina Nathania Gunawan,Universitas Widya Mandala Surabaya,Kedokteran,"Jombang, Jawa Timur",NaN,82234181771,@karina_nathania,Ingin S2 Di Korea,Kelas Reguler
30,2023-03-03 21:20:29,Januika Setiyawanti,Universitas Teknologi Yogyakarta,S1Akuntansi,Yogyakarta,NaN,81328108659,januika_setiyawanti,Mau Apply GksG Tahun Ini Jalur Univ,Kelas Reguler
29,2023-03-03 11:11:35,Yessica Ryanti Anggajaya,Universitas Mataram,Ilmu Komunikasi,Lombok,17.0,81339879390,Yessicaaang,Mempersiapkan Diri Untuk Pendaftaran Gks Tahun...,Kelas Reguler
17,2023-01-28 16:58:22,Sari Intan Romauli,Universitas Mikroskil,Manajemen Bisnis,Medan,17.0,895611078810,sariintan.61,Ingin Mendaftar Gks Ditahun 2023,Kelas Reguler

In [154]:
gks_g.to_csv('datacleaning_gksg.csv', index=False)

##Explore gks_sheet

In [156]:
gks_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 13 columns):
 #   Column                                                                                         Non-Null Count  Dtype
---  ------                                                                                         --------------  -----
 0   timestamp                                                                                      42 non-null     object
 1   nama_lengkap                                                                                   42 non-null     object
 2   asal_instansi                                                                                  42 non-null     object
 3   jurusan                                                                                        42 non-null     object
 4   domisili                                                                                       42 non-null     object
 5   umur                                                                                           42 non-null     object
 6   no._hp_aktif                                                                                   42 non-null     object
 7   nama_akun_instagram                                                                            42 non-null     object
 8   alasan_ingin_mengikuti_mentorship                                                              42 non-null     object
 9   pilihan_kelas                                                                                  32 non-null     object
 10  apakah_kamu_bersedia_melakukan_pembayaran_sebesar_rp200.000_untuk_kelas_reguler                42 non-null     object
 11  apakah_kamu_bersedia_menghadiri_onboarding_yang_akan_dilaksanakan_pada_tanggal_6_agustus_2022  42 non-null     object
 12  apakah_kamu_bersedia_mengikuti_mentorship_pada_tanggal_yang_sudah_ditentukan                   42 non-null     object
dtypes: object(13)
memory usage: 4.4+ KB

In [157]:
gks_sheet = gks_sheet.drop(columns=['apakah_kamu_bersedia_melakukan_pembayaran_sebesar_rp200.000_untuk_kelas_reguler'])
gks_sheet = gks_sheet.drop(columns=['apakah_kamu_bersedia_menghadiri_onboarding_yang_akan_dilaksanakan_pada_tanggal_6_agustus_2022'])
gks_sheet = gks_sheet.drop(columns=['apakah_kamu_bersedia_mengikuti_mentorship_pada_tanggal_yang_sudah_ditentukan'])

gks_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   timestamp                          42 non-null     object
 1   nama_lengkap                       42 non-null     object
 2   asal_instansi                      42 non-null     object
 3   jurusan                            42 non-null     object
 4   domisili                           42 non-null     object
 5   umur                               42 non-null     object
 6   no._hp_aktif                       42 non-null     object
 7   nama_akun_instagram                42 non-null     object
 8   alasan_ingin_mengikuti_mentorship  42 non-null     object
 9   pilihan_kelas                      32 non-null     object
dtypes: object(10)
memory usage: 3.4+ KB

In [158]:
gks_sheet = gks_sheet.rename(columns={'no._hp_aktif': 'nomor_hp'})
gks_sheet = gks_sheet.rename(columns={'nama_akun_instagram': 'nama_ig'})
gks_sheet = gks_sheet.rename(columns={'alasan_ingin_mengikuti_mentorship': 'alasan_join'})

gks_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      42 non-null     object
 1   nama_lengkap   42 non-null     object
 2   asal_instansi  42 non-null     object
 3   jurusan        42 non-null     object
 4   domisili       42 non-null     object
 5   umur           42 non-null     object
 6   nomor_hp       42 non-null     object
 7   nama_ig        42 non-null     object
 8   alasan_join    42 non-null     object
 9   pilihan_kelas  32 non-null     object
dtypes: object(10)
memory usage: 3.4+ KB

In [159]:
gks_sheet["timestamp"] = pd.to_datetime(gks_sheet["timestamp"])

gks_sheet["nama_lengkap"] = gks_sheet["nama_lengkap"].str.title()

gks_sheet["asal_instansi"] = gks_sheet["asal_instansi"].str.title()
gks_sheet["asal_instansi"] = gks_sheet["asal_instansi"].str.replace("-", "", regex=False)
gks_sheet.dropna(subset=["asal_instansi"], inplace=True)

gks_sheet["jurusan"] = gks_sheet["jurusan"].str.replace("-", "", regex=False)
gks_sheet.dropna(subset=["jurusan"], inplace=True)

gks_sheet["umur"] = gks_sheet["umur"].astype(str)
gks_sheet["umur"] = gks_sheet["umur"].str.replace("T", " ")

gks_sheet["domisili"] = gks_sheet["domisili"].str.title()

gks_sheet["alasan_join"] = gks_sheet["alasan_join"].str.replace("-", "", regex=False)
gks_sheet.dropna(subset=["alasan_join"], inplace=True)

In [161]:
gks_sheet["umur"] = gks_sheet["umur"].astype(str)
gks_sheet["umur"] = gks_sheet["umur"].str.replace("thn", " ")

In [162]:
gks_g["umur"] = gks_u["umur"].astype(int)

gks_g.umur.value_counts().sort_index()

17.0    5
18.0    7
19.0    7
20.0    1
21.0    2
22.0    3
24.0    2
27.0    1
28.0    1
Name: umur, dtype: int64

In [164]:
gks_sheet.sample(5)

,timestamp,nama_lengkap,asal_instansi,jurusan,domisili,umur,nomor_hp,nama_ig,alasan_join,pilihan_kelas
27,2022-03-08 22:37:14,Ihsani Yaomi Al-Afgani,Smkn 1 Cilimus (Sdg Bekerja),Tata boga (sudah lulus),Jawabarat (Skrg Sedang Bekerja Di Jakarta),19,89512878169,isnyao,Agar lebih terarah untuk pemberkasan cara pend...,Reguler
33,2022-04-08 16:20:40,Alfiana Yunike To,Univ. Brawijaya,,Kota Malang,19 tahun,81259020660,tteoktteok_12,Karena tahun ini akan mendaftar beasiswa GKS d...,NaN
9,2022-01-08 18:41:06,Yenty Gustia,Universitas Terbuka,Pendidikan Bahasa Inggris,Bogor,21,89647244748,yenty9_,Butuh referensi/review personal statement dan ...,Reguler
4,2022-07-31 22:19:55,Stephanie Candy Sabella,Sma Pahoa,IPS,Tangerang,18,81212850979,stephanie.cs,Sejak kecil saya selalu bermimpi agar bisa kul...,Premium
29,2022-03-08 23:21:21,Franky Sanjaya Galingging,Gap Year,IPA,Medan,18,82164262288,@frank.ysg,Karna Saya ingin kuliah ke luar negri. Dan say...,Reguler

In [165]:
gks_sheet.to_csv('datacleaning_gkssheet.csv', index=False)